# Site
name: 'Epic Games - Latest in Gaming & Tech'
description: 'Epic Games is your ultimate destination for discovering the latest and greatest in gaming and technology. Dive into a world of top-tier games, cutting-edge tech news, comprehensive reviews, insightful guides, and engaging community discussions.'
logo: 'assets/images/favicon.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
disqus: 'demowebsite'
email: 'exmgks@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    adam:
      name:           Adam
      site:           https://epicgames.in
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hello I am Adam, I write for Epic Games & Tech"
      email:          exmgks@gmail.com
      twitter:        
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: epic
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]